### ISSUE TITLE
why do you use Redis Pubsub

### ISSUE THREAD

**Issue by MaryLilian** [denosaurs/mess#1]
Hi, I am reading your project and I love this project
I have a question, why do you choose Redis Pubsub in your project instead of others like RabbitMQ or Kafka, are there any special features that others dont have it. Can you share me  it. I am wondering when I should choose Redis Pubsub instead of others like RabbitMQ or Kafka

**Comment by eliassjogreen** [comment]
Hello! Currently this project only supports RabbitMQ/AMQP 0.9.1 although support for more brokers are planned in the future to fit any projects specific needs. Among the planned brokers are Redis, MQTT and Kafka.
